import type { NextPage } from 'next'
import Head from 'next/head'
import ProductsList from '../components/ProductsList'

const Home: NextPage = () => {
   return (
      <div className='flex flex-col inset-0 fixed'>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <main>
            <ProductsList/>
         </main>
      </div>
   )
}

export default Home
